package io.github.gstojsic.bitcoin.proxy.model;

public enum BlockStatOptions {
    avgfee,
    avgfeerate,
    avgtxsize,
    blockhash,
    feerate_percentiles,
    height,
    ins,
    maxfee,
    maxfeerate,
    maxtxsize,
    medianfee,
    mediantime,
    mediantxsize,
    minfee,
    minfeerate,
    mintxsize,
    outs,
    subsidy,
    swtotal_size,
    swtotal_weight,
    swtxs,
    time,
    total_out,
    total_size,
    total_weight,
    totalfee,
    txs,
    utxo_increase,
    utxo_size_inc
}
